package com.example.n3cproject.ui.IcsRead;

public enum EventType {
    TP, COURS, COURS_TD, CM, EXAMEN, REUNION_RENCONTRE, CONTROLE_TERMINAL, SOUTENANCE, CONTROLE_PARTIEL, CONTROLE_CONTINU, CONSULTATION_DE_COPIES, TP_NON_ENCADRE, UNDETERMINED
}
